// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnmlfjqslsvxhgtbsppb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRubWxmanFzbHN2eGhndGJzcHBiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNjMwNjQsImV4cCI6MjA2NjkzOTA2NH0.7RSdOCwxPW5meq9Tbmp0JV8DTrbmVnEQROla89aDM4U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});